### ISSUE TITLE
Near Future IVAs display as black boxes

### ISSUE THREAD

**Issue by DaneHoffman** [post-kerbin-mining-corporation/NearFutureProps#47]
All IVAs display as a grid of black boxes. Issue is limited to Near Future parts only, stock IVAs still display properly. All IVAs from the near future series are displaying this way. 

These lines from the log appear to be related to the issue:

[WRN 12:49:07.268] InternalModel error: Part Crew capacity is 4, but 16 seats are defined in internal model
[WRN 12:49:07.273] InternalModel error: Part Crew capacity is 5, but 16 seats are defined in internal model

Steps attempted:
- Validate game files
- Remove all non-PKMC mods 
- Reinstall PKMC mods

KSP version: 1.12.2
[KSP.log](https://github.com/post-kerbin-mining-corporation/NearFutureProps/files/7071413/KSP.log)

![Screenshot (1)](https://user-images.githubusercontent.com/35747100/131229457-9650c47a-1c1b-4e82-bfda-2e7c3ec9abcf.png)
![Screenshot (2)](https://user-images.githubusercontent.com/35747100/131229469-d6004aff-b1ee-44b2-ae0b-1c10ec935417.png)

**Comment by ChrisAdderley** [comment]
Working as intended.

As per the changelog for the SSPX 2.0 release:
`- Added StationPartsExpansionIVAs Extra. This now contains the IVAs. By default, all IVAs now use the 'blank' internal space`

If you wish to have visible internals, install the extra.
